[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
    "wheel",
]
build-backend = "hatchling.build"

[project]
name = "OPTIMA"
description = "Aeronautical maintenance management software"
dependencies = [
    "Flask",
    "python-dotenv",
] 
    

requires-python = ">=3.6"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
readme = "README.md"
dynamic = [
    "version",
]
authors = [
    { name = "Santiago Trujillo", email = "santi.pilot04@gmail.com" },
    { name = "Gaston Umpierres", email = "gastonumpierres@gmail.com" },
]

[project.license]
file = "LICENSE"


[project.urls]
Homepage = "https://eltruji04.github.io/OPTIMA.github.io/"
Source = "https://github.com/eltruji04/OPTIMA"
Documentation = "https://github.com/eltruji04/OPTIMA-main"
Issues = "https://github.com/eltruji04/OPTIMA/issues"

# [project.scripts]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"

[tool.hatch.build.hooks.vcs]
version-file = "src/optima/version.py"
template = """
#!/usr/bin/env python3
'''
Version file automatically generated by setuptools-scm via hatch-vcs.
https://pypi.org/project/setuptools-scm/
https://github.com/ofek/hatch-vcs
Do not track this file and do not edit it manually.
'''
VERSION = {version!r}
VERSION_TUPLE = {version_tuple!r}
"""

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 100